### ISSUE TITLE
problem with s in basic mode!

### ISSUE THREAD

**Issue by saturn99** [glitchedgitz/cook#34]
run this command:
`cook a,A s,S`

we expectation print :
```
as
aS
As
AS
```

but output is:
```
a!
a#
a$
a%
a&
a(
...SNIP....
A^
A_
A`
A|
A~
A"
AS
```

I use cook Version 2.0

**Comment by glitchedgitz** [comment]
`s` is for special characters, so thats why its parsing all the special characters...

But then raw strings ```cook a,A `s`,S``` should have worked, but there is some bug here... I will fix it later

For now, you can use it like this ``` cook -var s a,A var,S```
