### ISSUE TITLE
Working with files and methods

### ISSUE THREAD

**Issue by oldDuDe124** [glitchedgitz/cook#36]
Hi
Thank you for providing this awesome tool!! 
I wanna merge 2 files with smart method but i don't know how, i have read your guide in the repository but still i'm a bit confused ....
Suppose that i have 2 wordlists (wordlist1 and wordlist2) , what is the command to merge 2 wordlists together using smart method? 
Thank you!

**Comment by oldDuDe124** [comment]
> Hey, Not sure if I get it. Can you give me an example?

Imagine that wordlist1 contains these words:
DomainName
DomainName1
DomainName2 
And so on ....
And wordlist2 contains
Account
Blog
Profile 
And so on....
I wanna merge these 2 wordlists together to get results like this:
Blog-DomainName
Blog_DomainName
Blog.DomainName 
Account_DomainName
......

I believe this can be done with smart method in cook or maybe i'm wrong! 

I'd appericate it if you can help me out!!

**Comment by glitchedgitz** [comment]
`smart method` is useful when you want to play with word cases

For what you want to do, you can use `-append`
https://github.com/glitchedgitz/cook#-append

And instead of `/` you can use `-,_,.` (list of chars you want, separated by comma)

**Comment by davidinfosec** [comment]
> Hey! I actually happen to make a tool that you might find useful for combining lists. It's called Domain Name Ninja. I saw your reply in my email and I couldn't help but recommend it. https://github.com/davidinfosec/domain-name-ninja
